const classes = JSON.stringify([
  "pre nursery",
  "pre nursery new admission",
  "pre nursery mercury",
  "pre nursery venus",
  "nursery 1",
  "nursery 1 new admission",
  "nursery 1 mercury",
  "nursery 1 venus",
  "nursery 1 mars",
  "nursery 2",
  "nursery 2 new admission",
  "nursery 2 mercury",
  "nursery 2 venus",
  "nursery 2 mars",
  "nursery 2 jupiter",
  "kindergaten",
  "kindergaten new admission",
  "kindergaten mercury",
  "kindergaten venus",
  "kindergaten mars",
  "kindergaten jupiter",
  "kindergaten earth",
  "lower basic 1",
  "lower basic 1 new admission",
  "lower basic 1 mercury",
  "lower basic 1 venus",
  "lower basic 1 mars",
  "lower basic 1 jupiter",
  "lower basic 2 mercury",
  "lower basic 2",
  "lower basic 2 new admission",
  "lower basic 2 venus",
  "lower basic 2 mars",
  "lower basic 2 jupiter",
  "lower basic 2 earth",
  "lower basic 3",
  "lower basic 3 new admission",
  "lower basic 3 mercury",
  "lower basic 3 venus",
  "lower basic 3 mars",
  "middle basic 4",
  "middle basic 4 new admission",
  "middle basic 4 mercury",
  "middle basic 4 venus",
  "middle basic 4 mars",
  "middle basic 4 jupiter",
  "middle basic 5",
  "middle basic 5 new admission",
  "middle basic 5 mercury",
  "middle basic 5 venus",
  "middle basic 5 mars",
  "middle basic 6",
  "upper jss 1",
  "upper jss 1 new admission",
  "upper jss 1 mercury",
  "upper jss 1 venus",
  "upper jss 1 mars",
  "upper jss 1 jupiter",
  "upper jss 2",
  "upper jss 2 new admission",
  "upper jss 2 mercury",
  "upper jss 2 venus",
  "upper jss 2 mars",
  "upper jss 2 jupiter",
  "upper jss 3",
  "upper jss 3 new admission",
  "upper jss 3 mercury",
  "upper jss 3 venus",
  "upper jss 3 mars",
  "upper jss 3 jupiter",
  "ss 1",
  "ss 1 new admission",
  "ss 1 mercury",
  "ss 1 venus",
  "ss 1 mars",
  "ss 1 jupiter",
  "ss 2",
  "ss 2 new admission",
  "ss 2 mercury",
  "ss 2 venus",
  "ss 2 mars",
  "ss 2 jupiter",
  "ss 3",
  "ss 3 new admission",
  "ss 3 mercury",
  "ss 3 venus",
  "ss 3 mars",
  "ss 3 jupiter",
]);
const fees = JSON.stringify([
  ["pre nursery", "60500"],
  ["nursery 1", "63500"],
  ["nursery 2", "63500"],
  ["kindergaten", "66500"],
  ["lower basic 1", "63500"],
  ["lower basic 2", "63500"],
  ["lower basic 3", "63500"],
  ["middle basic 4", "63500"],
  ["middle basic 5", "63500"],
  ["middle basic 6", "66500"],
  ["upper jss 1", "70500"],
  ["upper jss 2", "70500"],
  ["upper jss 3", "70500"],
  ["ss 1", "72500"],
  ["ss 2", "72500"],
  ["ss 3", "72500"],
  ["waec", "10000"],
  ["bece", "10000"],
  ["school uniform", "5000"],
  ["rardigan", "5000"],
]);

module.exports = {
    classes,
    fees
};
